### PR TITLE
Disabled conflicting background colors

### PR DESCRIPTION
**Pull request by burodepeper**
Updated the css because the default line height of 1.5 conflicted with some background colors, resulting in weird lines.

I wouldn't mind taking over the repo btw, to keep it alive. I believe it is as easy as selecting me as the owner somewhere on the repo settings page.

### CODE REVIEW

**Comment by ChiperSoft** [comment]
It looks like your master was out of date from mine, I can't merge it cleanly from github.

I'll go ahead and add you as a collaborator.

**Comment by burodepeper** [comment]
Ok, I'm still new to the actual collaborating part of git. What am I to do now?
Checkout the master repo, just add my changes there, and forget all about the fork and push?

**Comment by ChiperSoft** [comment]
You can do it two ways.

1. Merge my master into your master, correcting the merge conflict, and then push that up to github.  That will update this PR, which you can then merge yourself as a collaborator.

2. Clone my repo exactly as if it were your own, re-apply the changes, commit and push to master.

**Comment by burodepeper** [comment]
Ha, I'll go for the save option two! Thanks for the help.

**Comment by ChiperSoft** [comment]
Ok then, I'm closing this PR.

**Pull request closed without merging**
